landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name='home'),
]

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index, name= 'index'),
    # path('123', views.landing, name= 'landing'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<product_id>', views.product, name= 'product'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('products', include('products.urls')),
    path('orders', include('orders.urls')),

]

landing/models.py
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=128)

    # красивий вывод в админке
    # def __str__(self):
    #     return 'Имя:{}, E-mail: {}'.format(self.name, self.email)

orders/models.py
from django.db import models
from products.models import Product
from django.db.models.signals import post_save
class Status(models.Model):
    name = models.CharField(max_length=24,  blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

class Order(models.Model):
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    customer_name = models.CharField(max_length=64,  blank=True, null=True, default=None)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_phone = models.CharField(max_length=48, blank=True, null=True, default=None)
    customer_address = models.CharField(max_length=128, blank=True, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    # красивий вывод в админке
    def __str__(self):
        return 'Заказ:{}  {}'.format(self.id, self.status.name)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)

class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.PROTECT)
    number = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)# цена на за все количество * цену за единицу
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

        # красивий вывод в админке
    def __str__(self):
        return '{}'.format(self.product.name)

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price = price_per_item
        self.total_price = self.number * price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)

def product_in_order_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(order=order, is_active=True)

    order_total_price = 0
    for items in all_products_in_order:
        order_total_price += items.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)

post_save.connect(product_in_order_post_save, sender=ProductInOrder)

products/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64,  blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


class Product(models.Model):
    name = models.CharField(max_length=64,  blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.PROTECT)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    # красивий вывод в админке
    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='static/media/product_image')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '{}'.format(self.id)

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'

landing/forms.py
from django import forms
from .models import *

class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        exclude = ['']

orders/forms.py
from django import forms
from .models import *

# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = ['']

products/forms.py
from django import forms
from .models import *

# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = ['']

landing/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import SubscriberForm
from django.template import RequestContext
from products.models import *

def landing(request):
    form = SubscriberForm(request.POST or None)
    if request.method =='POST' and form.is_valid():
        data = form.cleaned_data
        print(data['name'])
        new_form = form.save()

    return render(request, 'landing/landing.html', locals(), RequestContext(request))

def home(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_phone = products_images.filter(product__category__name='Телефоны')
    products_images_laptops = products_images.filter(product__category_id=2)
    return render(request, 'landing/home.html', locals(), RequestContext(request))

products/views.py
from django.shortcuts import render
from products.models import *

def product(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'landing/product.html', locals())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>

    <div class="wrapper">
        <div class="wraper-content">
        {% include 'navbar.html' %}


        {% block content %}
        {% endblock content %}
        </div>
    </div>

     {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="text">
            <h3>FOOTER</h3>
        </div>
    </div>
</footer>

templates/landing/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="section-top">
        <img src="{% static 'img/slider0.jpg' %}" class="img-fluid">
    </div>
    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Новые поступления
                    </h1>
                </div>
                    {% for product_image in products_images %}
                        {% include 'landing/product_item.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="section section-delivery">
        <div>
            <h3>Free shopping</h3>
        </div>
    </div>

    <div class="section section2 phones-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Телефоны
                    </h1>
                </div>
                    {% for product_image in products_images_phone %}
                        {% include 'landing/product_item.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="section section3 laptops-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Ноутбуки
                    </h1>
                </div>
                    {% for product_image in products_images_laptops %}
                        {% include 'landing/product_item.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

templates/landing/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'landing.css' %}">

</head>
<body>

<div class="general-container">
    <div class="container top-container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="title">Наш магазин скоро откроеться оставляйте ваш E-mail </h1>
                <div>
                    <form action="" method="post">{% csrf_token %}
                      <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" name="{{ form.email.name }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                      </div>
                      <div class="form-group">
                        <label for="exampleInputName">Name</label>
                        <input type="text" name="{{ form.name.name }}" class="form-control" id="exampleInputName" placeholder="Name">
                      </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

templates/landing/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <img src="{{ image_item.image.url }}" class="img-fluid">
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <div class="">
                    {{ product.description }}
                </div>

                <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#description" role="tab" aria-controls="home" aria-selected="true">Описание</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#delivery" role="tab" aria-controls="profile" aria-selected="false">Доставка</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"></a>
                  </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="home-tab">{{ product.description }}</div>
                  <div class="tab-pane fade" id="delivery" role="tabpanel" aria-labelledby="profile-tab"></div>
                  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
                </div>

            </div>
        </div>
    </div>
{% endblock content %}

templates/landing/product_item.html
<div class="col-lg-3">
    <div class="product-item">
        <div>
{# создаем ссылку при нажатии на картинку . первый параметр это имя ф-и во views "product' и передает второй параметр id #}
            <a href="{% url 'product' product_image.product.id %}">
                <img src="{{ product_image.image.url }}" class="img-fluid">
            </a>
        </div>
        {% if product_image.product.discount %}
            <div class="discount_container">
                <span>{{ product_image.product.discount }}%</span>
            </div>
        {% endif %}
        <h6>{{ product_image.product.name }}</h6>
        <p>{{ product_image.product.description|truncatechars_html:70 }}</p>
        <div>
            {{ product_image.product.price }} UAH
        </div>
        <div class="add-to-card-btn">
            <button class="btn btn-success">
                Добавить в корзину
            </button>
        </div>
    </div>
    </div>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="#">Top navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/home">Домой <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>